### ISSUE TITLE
Design standards

### ISSUE THREAD

**Issue by mtempinski** [helllomatt/Theamus#120]
In order to have features look proper on _all_ themes and templates, there needs to be a design standard in some fashion or another. (for Theamus specifically!)

I was thinking of using something like "cards" for layouts. Basically they would just be sections of a page that can be styled by the theme developer. Each "card" would house specific content in relation to that card.

For example, we can create a blog post. Right now it's just a form with sectioned off form groups which doesn't look bad, but can't remain consistently beautiful on all websites. If we switch that to the card format, each form group would be a card because it's relevant to _one_ topic in the form.

    <form>
        <title card>
            -title input-

            <card expand>
                -permalink input-
                -browser title input-
            </card expand>
        </title card>
    </form>

Now that gives a prettier view model to the title form since it's more organized that way instead of being in a giant form.

**Comment by helllomatt** [comment]
Oh, done did this with pull request #121.
